### ISSUE TITLE
Cookie format doesnt match

### ISSUE THREAD

**Issue by itslifesaidhe** [M-rcus/OnlyFans-Cookie-Helper#1]
The way the text is formatted, or the order of the values rather, doesnt work as a direct copy paste, have to go through and fill in each one individually - still very handy!

**Comment by M-rcus** [comment]
Not sure what you mean?  
The order of the values don't matter (for instance, `auth_hash` being at the top makes no difference to it being in the middle).

I just tried it myself by copying and pasting it into my `extra_auth.json` without any issues whatsoever.

**Comment by itslifesaidhe** [comment]
Weird; when I copy pasted the whole bit directly placing the one in the file, I got auth errors - the script said something about “expecting XXX at XXX line...” etc etc

Then when I kept it the same, and copy pasted just the values into the original locations, it worked fine

**Comment by M-rcus** [comment]
Could you try it again and see if you still get the issue?

If so, send a screenshot (but censor/blur out the values so you don't leak your credentials) with how your whole file is formatted.
