### ISSUE TITLE
GPT chat connecting to a website

### ISSUE THREAD

**Issue by doctorregina** [M-rcus/OnlyFans-Cookie-Helper#11]
Hiii,

I have an OnlyFans agency and I would be happy to build Python script to automate chatting with costumers via GPT chat.
Could you please help me to create this code? As far as I know there are some difficulties with API in Onlyfans website so the data could only be transferred by data scrapping, am I right?

**Comment by M-rcus** [comment]
> Could you please help me to create this code?

Nope.

> As far as I know there are some difficulties with API in Onlyfans website so the data could only be transferred by data scrapping, am I right?

I don't know. I have no experience with the OnlyFans API and this extension doesn't do any "scraping" (it only retrieves data stored in the user's browser).
