### ISSUE TITLE
Auth Issues

### ISSUE THREAD

**Issue by j-ktz** [M-rcus/OnlyFans-Cookie-Helper#6]
Installed the new version of OnlyFans ripper, followed instructions, copy/pasted auth info from latest version of Cookie Helper and still have Auth Issues, errors. Any ideas?

**Comment by M-rcus** [comment]
Is it the "Please refresh the page" error? In that case, it's related to https://github.com/DIGITALCRIMINAL/OnlyFans/issues/1078

**Comment by j-ktz** [comment]
@M-rcus Thanks for responding. I've tried everything. No it's the error that goes:
"Auth (V1) Attempt 1/10
Auth (V1) Attempt 2/10
Auth (V1) Attempt 3/10
Auth (V1) Attempt 4/10
Auth (V1) Attempt 5/10
Auth (V1) Attempt 6/10
Auth (V1) Attempt 7/10
Auth (V1) Attempt 8/10
Auth (V1) Attempt 9/10
Auth (V1) Attempt 10/10
Scraping Subscriptions
There's nothing to scrape."

**Comment by M-rcus** [comment]
Without any real errors I can't really tell if it's caused by the addon or not, but I assume it's not related to the addon, as the OnlyFans scraper doesn't work at all at the moment.

I'd keep an eye on that issue and wait for a fix to be released and try again.

**Comment by toomanydevils** [comment]
> Without any real errors I can't really tell if it's caused by the addon or not, but I assume it's not related to the addon, as the OnlyFans scraper doesn't work at all at the moment.
> 
> I'd keep an eye on that issue and wait for a fix to be released and try again.

My cookie helper works fine, just have other issues with the scrapper lol

**Comment by M-rcus** [comment]
> > Without any real errors I can't really tell if it's caused by the addon or not, but I assume it's not related to the addon, as the OnlyFans scraper doesn't work at all at the moment.
> > I'd keep an eye on that issue and wait for a fix to be released and try again.
> 
> My cookie helper works fine, just have other issues with the scrapper lol

There are some ongoing issues with the scraper software that are still work-in-progress.

You can try to [download the latest version from the `master` branch](https://github.com/DIGITALCRIMINAL/OnlyFans/archive/refs/heads/master.zip), which seems to at least work somewhat.  
Granted it's still being worked on (latest change was around 34 minutes ago as of this comment), so it's not completely fixed yet. I suggest keeping an eye on the [open GitHub issues for the scraper project](https://github.com/DIGITALCRIMINAL/OnlyFans/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for updates regarding that.

**Comment by toomanydevils** [comment]
> > > Without any real errors I can't really tell if it's caused by the addon or not, but I assume it's not related to the addon, as the OnlyFans scraper doesn't work at all at the moment.
> > > I'd keep an eye on that issue and wait for a fix to be released and try again.
> > 
> > 
> > My cookie helper works fine, just have other issues with the scrapper lol
> 
> There are some ongoing issues with the scraper software that are still work-in-progress.
> 
> You can try to [download the latest version from the `master` branch](https://github.com/DIGITALCRIMINAL/OnlyFans/archive/refs/heads/master.zip), which seems to at least work somewhat.
> Granted it's still being worked on (latest change was around 34 minutes ago as of this comment), so it's not completely fixed yet. I suggest keeping an eye on the [open GitHub issues for the scraper project](https://github.com/DIGITALCRIMINAL/OnlyFans/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) for updates regarding that.

Yeah, I had got mine figured out not long after my comment, In regard to my comment, it was more an affirmation that your cookie helper was working fine, and that problems J-ktz was experiencing were not just localized to them.
