### ISSUE TITLE
Chrome reports errors with extension, but operates correctly.

### ISSUE THREAD

**Issue by Tyemnata** [M-rcus/OnlyFans-Cookie-Helper#8]
Error 1:
"Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details."

Error 2:

"Permission 'contextualIdentities' is unknown or URL pattern is malformed."
line 19 "contextualIdentities"

**Comment by M-rcus** [comment]
The first one is something I need to look more into (I'm actually not sure I need to do any changes besides updating the `manifest_version` number used in the extension).

The second error is a known issue documented in the README: https://github.com/M-rcus/OnlyFans-Cookie-Helper#chrome--brave  
If it bothers you, you can open the `manifest.json` file and then remove the line that says `contextualIdentities`, plus the comma before that line:

Before:
![](https://m.leak.fans/ss/2022-07-16_U0jamg.png)

After:
![](https://m.leak.fans/ss/2022-07-16_RP0Vrd.png)  
**Note how `"storage"` doesn't have a comma after it anymore**

**Comment by M-rcus** [comment]
Hi, sorry this took me so long. This should be fixed as of [v2.2.0](https://github.com/M-rcus/OnlyFans-Cookie-Helper/releases/tag/2.2.0) :)
